### ISSUE TITLE
text fixup

### ISSUE THREAD

**Issue by jskrzypek** [mcfly-io/mcflyio-web#3]
https://github.com/mcfly-io/mcflyio-web/blob/master/client/scripts/common/views/home.html#L56-L57
Suggestions:

*MCFLY is a javascript full stack platform for building easily realtime mobile hybrid and web single page app using latest (but mainstream) libraries and framework.*

*We are not a new platform, we are the glue that connects together awesome frameworks to give you the best possible experience in the minimum time.*

My suggestion:

MCFLY is a full-stack javascript platform for painlessly building realtime hybrid mobile and single page apps using the latest mainstream libraries and frameworks, giving you maximum development power in minimum time.

We are not a new awesome framework. We are the glue between awesome frameworks.

**Comment by thaiat** [comment]
done
